### ISSUE TITLE
是否能用在别的平台上，比如windows,mac,linux？

### ISSUE THREAD

**Issue by lzy83925** [AnJoiner/FFmpegCommand#16]
这个工具是否能用在别的平台上，比如windows,mac,linux？

**Comment by AnJoiner** [comment]
当前工具只适用于Android平台。
Linux : sudo apt-get install ffmpeg
其他平台可以参考 [FFmpeg-Build](https://ffmpeg.zeranoe.com/builds/) ，这上面是已经编译好的了
