### ISSUE TITLE
关于增减编解码

### ISSUE THREAD

**Issue by spysoos** [AnJoiner/FFmpegCommand#18]
如果想精简一些编码器或者增加更多的编解码要如何操作呢？

**Comment by spysoos** [comment]
另外，请问能把各个 so文件打包成一个大的so文件吗？

**Comment by AnJoiner** [comment]
> 如果想精简一些编码器或者增加更多的编解码要如何操作呢？

这个需要在编译ffmpeg的时候进行配置

**Comment by AnJoiner** [comment]
> 另外，请问能把各个 so文件打包成一个大的so文件吗？

可以的，也需要进行配置编译可以打包成一个文件
