### ISSUE TITLE
添加水印成功，但是速度很慢，而且没有进度提示了

### ISSUE THREAD

**Issue by xue12311** [AnJoiner/FFmpegCommand#19]
添加水印成功，但是速度很慢，而且没有进度提示了

**Comment by AnJoiner** [comment]
> 添加水印成功，但是速度很慢，而且没有进度提示了

补充一下你使用的版本、命令、使用的cpu-abi

**Comment by maomao-creat** [comment]
1.1.5  添加水印没有进度 ,到100才会回调

**Comment by AnJoiner** [comment]
> 1.1.5 添加水印没有进度 ,到100才会回调

1.2.0版本已修复
