### ISSUE TITLE
两个音频文件混音时长问题

### ISSUE THREAD

**Issue by zaaach** [AnJoiner/FFmpegCommand#20]
有a、b两个mp3文件，a时长2分钟，b时长1分钟，b作为背景音进行混音，如何让b循环呢？
```
ffmpeg -y -i %s -i %s -filter_complex amix=inputs=2:duration=first %s
```
现在用的上面命令，混音完成后面就没有背景音了

**Comment by AnJoiner** [comment]
根据你的问题，你可以试试这样处理：
* 先将b进行拼接，即是 b 拼接 b 形成一个2分钟的 c
* 再将 a和c 进行混音

**Comment by AnJoiner** [comment]
> 有a、b两个mp3文件，a时长2分钟，b时长1分钟，b作为背景音进行混音，如何让b循环呢？
> 
> ```
> ffmpeg -y -i %s -i %s -filter_complex amix=inputs=2:duration=first %s
> ```
> 
> 现在用的上面命令，混音完成后面就没有背景音了

https://github.com/AnJoiner/FFmpegCommand/issues/20#issuecomment-653347482

**Comment by zaaach** [comment]
感谢回复！我先试试

**Comment by zaaach** [comment]
大佬你好，还想请教个问题就是合成mp3的同时调整背景音的音量：
```
ffmpeg -y -i %s -i %s -filter_complex [0]volume=1,pan=2c[a];[1]volume=%f,pan=2c[b];[a][b]amix=duration=first -ac 2 -c:a libmp3lame -q:a 3 %s
```
我用上面命令，合成之后的音频没有声音了

**Comment by AnJoiner** [comment]
> 大佬你好，还想请教个问题就是合成mp3的同时调整背景音的音量：
> 
> ```
> ffmpeg -y -i %s -i %s -filter_complex [0]volume=1,pan=2c[a];[1]volume=%f,pan=2c[b];[a][b]amix=duration=first -ac 2 -c:a libmp3lame -q:a 3 %s
> ```
> 
> 我用上面命令，合成之后的音频没有声音了

一般我不建议你这样做，可以分步骤进行操作:  
* 先对背景音乐进行降音   
* 再对两个音频进行合并

**Comment by zaaach** [comment]
好的，谢谢！
