### ISSUE TITLE
获取视频分辨率之类信息 怎么全是负值long

### ISSUE THREAD

**Issue by z8806c** [AnJoiner/FFmpegCommand#23]
获取视频分辨率之类信息 怎么全是负值long

**Comment by AnJoiner** [comment]
> 获取视频分辨率之类信息 怎么全是负值long

感谢你的反馈，下个版本解决这个问题

**Comment by AnJoiner** [comment]
> 获取视频分辨率之类信息 怎么全是负值long

在1.1.6版本已解决这个问题
