### ISSUE TITLE
可以支持Android10级以上版本么

### ISSUE THREAD

**Issue by Yumore** [AnJoiner/FFmpegCommand#30]
我尝试着将编译版本升级到29的时候运行直接报错，请问什么时候能支持target=29呢

**Comment by AnJoiner** [comment]
> 我尝试着将编译版本升级到29的时候运行直接报错，请问什么时候能支持target=29呢

demo就是target=29的，你检查一下你的权限配置

**Comment by Yumore** [comment]
抱歉 我之前是taget设置成了30   改到29就好了
