### ISSUE TITLE
本地文件名称有空格，执行ffmpeg命令处理时，报 No such file or directory

### ISSUE THREAD

**Issue by sunshengfei** [AnJoiner/FFmpegCommand#32]
类似地，在电脑上可以加双引号、单引号或转义符解决
如：
```
ffmpeg -y -i "IMG_0946 (1).mov" -vcodec copy -acodec copy 1111.mp4
ffmpeg -y -i 'IMG_0946 (1).mov' -vcodec copy -acodec copy 1111.mp4
ffmpeg -y -i IMG_0946\ (1).mov -vcodec copy -acodec copy 1111.mp4
```

但在手机上：

单双引号和转义符均被空格截断，导致提示文件`IMG_0946` No such file or directory。

我猜可能是jni层需要修改下，期待解决，谢谢

**Comment by AnJoiner** [comment]
> 类似地，在电脑上可以加双引号、单引号或转义符解决
> 如：
> 
> ```
> ffmpeg -y -i "IMG_0946 (1).mov" -vcodec copy -acodec copy 1111.mp4
> ffmpeg -y -i 'IMG_0946 (1).mov' -vcodec copy -acodec copy 1111.mp4
> ffmpeg -y -i IMG_0946\ (1).mov -vcodec copy -acodec copy 1111.mp4
> ```
> 
> 但在手机上：
> 
> 单双引号和转义符均被空格截断，导致提示文件`IMG_0946` No such file or directory。
> 
> 我猜可能是jni层需要修改下，期待解决，谢谢

好的，感谢反馈

**Comment by patrickstar007** [comment]
还没解决吗。。。

**Comment by AnJoiner** [comment]
> 还没解决吗。。。

在1.3.0版本已修复
