### ISSUE TITLE
不能执行

### ISSUE THREAD

**Issue by zhangsuper** [AnJoiner/FFmpegCommand#4]
集成后调用FFmpegCommand.runAsync崩溃,这是咋回事啊

**Comment by zhangsuper** [comment]
建个交流群呗，方便交流

**Comment by AnJoiner** [comment]
好的，你先看一下是否是使用Android10，如果是Android10需要加入新的权限判断，在【常见问题】中写了的。

**Comment by AnJoiner** [comment]
QQ 群聊 ：439706357
