### ISSUE TITLE
build failed of ffmpeg-invoke.cpp file 

### ISSUE THREAD

**Issue by mansiJspaceo** [AnJoiner/FFmpegCommand#7]
while build ffmpeg-invoke.cpp file got this error

Change ndk version also again build android folder inside ffmpeg source code

**/ffmpeg/libavutil/x86/timer.h:39:23: error: invalid
output constraint '=a' in asm
:"=a" (a), "=d" (d));**

also another error is

**libavcodec/x86/mathops.h:118:12: error: invalid
input constraint 'ic' in asm
: "ic" ((uint8_t)(-s))**

another is

**ffmpeg/libavcodec/x86/mathops.h:127:12: error: invalid
input constraint 'ic' in asm
: "ic" ((uint8_t)(-s))**

How can i solve it. plase help  

Thank you in Adavance

**Comment by AnJoiner** [comment]
Please tell me about your compilation environment, i will try it.
And You can use CMake to compile in Android Studio first, it can help you debug well

**Comment by AnJoiner** [comment]
I compile without problems, you can refer to this document[FFmpeg4.2.2-Build](https://github.com/AnJoiner/FFmpegCommand/blob/master/FFmpeg4.2.2-Build.md)

**Comment by mansiJspaceo** [comment]
i build with this ..but there are only generate with armani-7a .. when i built arm64-8a it's give a error... not build ffmpeg-invoke.so file.

Any idea for this how can we build for this

**Comment by mansiJspaceo** [comment]
i build with this ..but there are only generate with armani-7a .. when i
built arm64-8a it's give a error... not build ffmpeg-invoke.so file.

Any idea for this how can we build for this

**Comment by AnJoiner** [comment]
In fact compiling armeabi-v7a is enough, but using the latest version of ndk to compile arm64-v8a will give an error. I used ndk-14b to compile successfully, you can try it.

**Comment by mansiJspaceo** [comment]
okay..

but in latest device support arm64-v8a ... that's why..

if you have idea about which ndk version & ffmpeg verison build
successfully for all  armeabi-v7a, armeabi-v7a,x86,x64-86....

so i used this build again

**Comment by mansiJspaceo** [comment]
hello successfully build all file now...when i run ffmpeg command can not create output file 
what i have to do for that
